#!/bin/bash
########################
# For using kubernetes
########################
# Installing pip for Python 3
sudo apt update
sudo apt install python3-pip
# Installing pip for Python 2
sudo apt install python-pip

# Install docker
# Uninstall old versions
sudo apt-get remove docker docker-engine docker.io containerd runc
# Update the apt package index and install packages to allow apt to use a repository over HTTPS:
sudo apt-get update
sudo apt-get install \
    apt-transport-https \
    ca-certificates \
    curl \
    gnupg-agent \
    software-properties-common
curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
# searching for the last 8 characters of the fingerprint.
sudo apt-key fingerprint 0EBFCD88
# Use the following command to set up the stable repository. 
sudo add-apt-repository \
   "deb [arch=amd64] https://download.docker.com/linux/ubuntu \
   $(lsb_release -cs) \
   stable"
# INSTALL DOCKER ENGINE
sudo apt-get update
sudo apt-get install docker-ce docker-ce-cli containerd.io
# Verify that Docker Engine is installed correctly by running the hello-world image.
sudo docker run hello-world

# Run this command to download the current stable release of Docker Compose:
sudo curl -L "https://github.com/docker/compose/releases/download/1.25.5/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
# Apply executable permissions to the binary:
sudo chmod +x /usr/local/bin/docker-compose
# Test installation:
docker-compose --version


# Install Minikube: This is the tool you'll use to run Kubernetes locally, for your OS.
# Before you begin: To check if virtualization is supported on Linux, run the following command and verify that the output is non-empty:
grep -E --color 'vmx|svm' /proc/cpuinfo
# Installing minikube:
# 1-Install kubectl:
curl -LO https://storage.googleapis.com/kubernetes-release/release/`curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt`/bin/linux/amd64/kubectl
chmod +x ./kubectl
sudo mv ./kubectl /usr/local/bin/kubectl
kubectl version --client

https://medium.com/@joseignaciocastelli92/how-to-make-your-first-local-cluster-with-kubernetes-e15fc4b262e7
